### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Bobby4545** [SIsilicon/WorldEdit-BE#16] opened 2021-11-09 19:59 UTC
When i type and enter ;wand nothing happens
I tagged myself as builder and i was holding an wooden axe in my hand

**Comment by SIsilicon** [comment] 2021-11-09 20:45
Try installing the addon on the aternos server and see if it works there. If so, you might've set it up improperly on your end, or Minecraft somehow isn't working well for you. I received this issue before, where the addon doesn't work for some people yet works for others.

**Comment by SIsilicon** [comment] 2021-11-09 20:45
So try using aternos as instructed in the README.

**Comment by SIsilicon** [comment] 2021-11-09 21:37
Duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/7

**Closed by SIsilicon** 2021-11-09 21:37 UTC
Labels: bug, duplicate
