### ISSUE TITLE
Commands aren't working

### ISSUE THREAD

**Issue by shescanaan** [SIsilicon/WorldEdit-BE#152] opened 2023-01-10 07:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I installed the mod, started up a world, turned on experimental, activated both resource and behavior packs, yet none of the commands are working?? I've searched for this a bit and haven't found anything on it really, no youtube tutorials on how to even work the very basics of the app and workarounds if you're having issues. So I'm assuming this is a bug, for example: when I enter the command ;kit nothing happens. When I enter the tag "/tag @s add worldedit" it says the tag is added but no automated text saying I was given permissions.

### Expected behaviour

When entering the command ";kit" user should receive the basic worldedit kit. 

### Minecraft version

1.19.5

**Comment by SIsilicon** [comment] 2023-01-10 18:20
What are the experimental features you have enabled?

**Comment by SIsilicon** [comment] 2023-01-10 18:23
Respond in this other issue since this is a duplicate of it.
https://github.com/SIsilicon/WorldEdit-BE/issues/134

**Closed by SIsilicon** 2023-01-10 18:23 UTC
Labels: bug

**Comment by vermileoo** [comment] 2023-01-17 09:44
> 

having the same issue :( i enabled the experimental features: Holiday Creator Features, Beta APIs
