### ISSUE TITLE
Not working on 1.20.72

### ISSUE THREAD

**Issue by ProCool2184** [SIsilicon/WorldEdit-BE#247] opened 2024-03-26 19:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The tag command doesn't work and ; kit and every command and item 

### Expected behaviour

The tag command must work and ; kit and every command and item 

### Minecraft version

1.20.72

### Device and operating system

Xbox series s

**Comment by SIsilicon** [comment] 2024-03-31 22:23
Practically a duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/241

**Closed by SIsilicon** 2024-03-31 22:23 UTC
Labels: bug
