### ISSUE TITLE
The particle effect of the selection area is not displayed on server

### ISSUE THREAD

**Issue by Kreswanan** [SIsilicon/WorldEdit-BE#167] opened 2023-02-05 14:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

This problem doesn't happen all the time, but after the server has been running for a while and some people have used worldedit.
And try to continue to fill the square when the bug occurs, it will prompt **"0 blocks have been changed"**. 
To return to normal, you must restart the server or enter **"reload"** in the server console, but after a while the same problem occurs again.

### Expected behaviour

Unless it is turned off by itself, the particle effect of the selection should be displayed normally

### Content logs

_The server cannot record content logs, I logged this information from bds._
21:30:22 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"Finished!","with":[]},{"text":"\n████████████████████ 100.00%"}]}
21:30:22 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"commands.blocks.wedit:changed","with":["0"]}],"lastElementIdx":0}
21:30:22 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"Finished!","with":[]},{"text":"\n████████████████████ 100.00%"}]}
21:30:22 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"commands.blocks.wedit:changed","with":["0"]}],"lastElementIdx":0}
21:30:23 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"Finished!","with":[]},{"text":"\n████████████████████ 100.00%"}]}
21:30:23 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"commands.blocks.wedit:changed","with":["0"]}],"lastElementIdx":0}
21:30:23 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"Finished!","with":[]},{"text":"\n████████████████████ 100.00%"}]}
21:30:23 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"commands.blocks.wedit:changed","with":["0"]}],"lastElementIdx":0}
21:30:23 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"Finished!","with":[]},{"text":"\n████████████████████ 100.00%"}]}
21:30:23 INFO [Command] <ChristianBez787> /titleraw @s actionbar {"rawtext":[{"translate":"commands.blocks.wedit:changed","with":["0"]}],"lastElementIdx":0}

### Minecraft version

1.19.51

### Device and operating system

Windows Server 2022/Bedrock Dedicated Server

### Additional info

_This is the screen recording when the error occurs_
https://clipchamp.com/watch/OwrKraKucNn

**Comment by SIsilicon** [comment] 2023-02-05 20:36
Do you think you can attempt to reproduce it with a fixed amount of steps? That way I can reliably reproduce it as well.

**Comment by Kreswanan** [comment] 2023-02-06 00:12
I don't think so, the problem seems to only occur on the server, and there are no absolute steps to reproduce.  Usually it will appear after a period of normal use, sometimes the error will appear quickly and sometimes slowly, and it will definitely appear in the end.

**Comment by SIsilicon** [comment] 2023-02-06 01:52
As in, the end dimension?

**Comment by Kreswanan** [comment] 2023-02-06 07:43
Sorry I don't quite understand what you mean, English is not my mother tongue, what does _the end dimension_ mean?

**Comment by Kreswanan** [comment] 2023-02-06 07:49
If you're referring to the phrase "it will definitely appear in the end", it means that this error will always appear at the end, not "the End" dimension in the game.

**Comment by Kreswanan** [comment] 2023-02-09 16:15
Hope you are still following this question :)

**Comment by SIsilicon** [comment] 2023-02-11 21:46
@Kreswanan I'm having problems trying to reproduce it. How long does it usually take for the particles to disappear? And if not long, could you make a video the bug happening the moment the script is loaded?

**Comment by benmahler** [comment] 2023-04-02 09:36
I have a similar issue. Have not been able to see the selection particle effects at all since updating from 0.6 to 0.7. If I find a fix I'll post it here / link to a new issue that's a closer fit.

**Comment by benmahler** [comment] 2023-04-02 09:40
Selection particles do appear for the paste tool, and toggle with `;drawsel` as expected.

**Comment by Kreswanan** [comment] 2023-06-17 16:32
When this error occurs, the following error message will appear in the bds panel
![屏幕截图 2023-06-17 235006](https://github.com/SIsilicon/WorldEdit-BE/assets/101116355/85d2dbbb-9fba-4e69-ac81-d181011769c5)

**Comment by SIsilicon** [comment] 2023-12-08 18:21
Does this still happen in the latest version?

**Comment by SIsilicon** [comment] 2024-03-03 22:54
Closing now

**Closed by SIsilicon** 2024-03-03 22:54 UTC
Labels: bug, confirmed
