### ISSUE TITLE
worldedit doesn't work for me

### ISSUE THREAD

**Issue by gdcolo1** [SIsilicon/WorldEdit-BE#170] opened 2023-02-16 06:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

i am on mobile and

### Expected behaviour

For it to work

### Steps to reproduce

1. play on 1.19.50 or 1.19.51 (i forgot)
2. turn on the mod and all the experiments (not the custom biomes)
3. not turning on require resources
4. join the world, do /tag @s add worldedit
5. get a wooden axe
6. worldedit doesnt work
7. done

### Minecraft version

1.19.50

### Device and operating system

Realme c25s, android 11 i think

**Comment by SIsilicon** [comment] 2023-02-16 15:24
Duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/134

**Closed by SIsilicon** 2023-02-16 15:24 UTC
Labels: bug
