### ISSUE TITLE
Commands Not Working

### ISSUE THREAD

**Issue by ItzMazenWWE** [SIsilicon/WorldEdit-BE#12] opened 2021-10-31 15:24 UTC
I did /tag @s add builder
So I typed ;wand and :wand and /wand and it didn’t work.

**Comment by SIsilicon** [comment] 2021-10-31 16:19
Duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/7.

**Closed by SIsilicon** 2021-10-31 16:19 UTC
