### ISSUE TITLE
Worldedit not working with update 1.19.70

### ISSUE THREAD

**Issue by rankieth** [SIsilicon/WorldEdit-BE#174] opened 2023-03-15 19:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The wand tool no longer works, nothing works actually

### Expected behaviour

It should work

### Steps to reproduce

1. Update Bedrock edition
2. Load a world with the addon already enabled
3. Try and use it

### Minecraft version

1.19.70

### Device and operating system

Windows 11

**Comment by Rd-Coder** [comment] 2023-03-27 22:07
The same is happening to me, so here are some additional informations about the bug:

### Current behaviour

First of all the resource pack named "WorldEdit Bedrock Edition [RES]" throws the following warning:
`Missing dependency with ID '3cdb2ddf-662e-4f8f-a0a1-1293b91ccb2f' and version '0.7.2'.
`
That is the WorldEdit behavior pack UUID, which is not being recognized by the resource pack.

Secondly, the feature `Molang` was printing many errors to the log file, which I assumed that was due to the option `Molang Features` being desactivated in the world settings. After it being enabled those errors were resolved, however a new error was thrown from `Scripting`. Both logs can be found below.


### Steps to reproduce

1. Disable the option `Settings > Game > Experimental > Molang features`;
2. Activate both behaviour and resource pack (v0.7.2);
4. Open the world and check the log file;
5. Exit the world;
6. Activate `Molang features`;
7. Reopen the world and check the log file.

### Content logs

- Before enabling `Molang Features`:

```
[Molang][error]-WorldEdit_test | /storage/emulated/0/Android/data/com.mojang.minecraftpe/files/games/com.mojang/minecraftWorlds/QOohZMPSAAA=/behavior_packs/WorldEditB/animation_controllers/biome_detector.ac.json | animation_controllers | controller.animation.biome | states | default | transitions | ocean | query.biome_has_all_tags('ocean') == 1 && query.biome_has_any_tag('deep', 'warm', 'frozen', 'lukewarm', 'cold') == 0 | unrecognized token: query.biome_has_all_tags('ocean') == 1 && query.biome_has_any_tag('deep', 'warm', 'frozen', 'lukewarm', 'cold') == 0

[Molang][error]-WorldEdit_test | /storage/emulated/0/Android/data/com.mojang.minecraftpe/files/games/com.mojang/minecraftWorlds/QOohZMPSAAA=/behavior_packs/WorldEditB/animation_controllers/biome_detector.ac.json | animation_controllers | controller.animation.biome | states | default | transitions | plains | query.biome_has_all_tags('plains') == 1 && query.biome_has_any_tag('mutated') == 0 | unrecognized token: query.biome_has_all_tags('plains') == 1 && query.biome_has_any_tag('mutated') == 0

[Molang][error]-WorldEdit_test | /storage/emulated/0/Android/data/com.mojang.minecraftpe/files/games/com.mojang/minecraftWorlds/QOohZMPSAAA=/behavior_packs/WorldEditB/animation_controllers/biome_detector.ac.json | animation_controllers | controller.animation.biome | states | default | transitions | desert | query.biome_has_all_tags('desert') == 1 && query.biome_has_any_tag('mutated', 'hills') == 0 | unrecognized token: query.biome_has_all_tags('desert') == 1 && query.biome_has_any_tag('mutated', 'hills') == 0
...
```
Remaining logs have been omitted for the sake of simplicity, because they have the same template.


- After enabling `Molang Features`:

```
[Scripting][error]-Plugin [WorldEdit Bedrock Edition - 1.0.0] - [server/index.js] ran with error: [[object Object]]
```


### Minecraft version

1.19.70.20


### Device and operating system

Samsung SM-A307GT, Android 11

**Comment by SIsilicon** [comment] 2023-06-20 13:06
Duplicate of mentioned post.
If you're having problems with latest WorldEdit post, feel free to make a new post, assuming one wasn't already made

**Closed by SIsilicon** 2023-06-20 13:06 UTC
Labels: bug
