### ISSUE TITLE
Commands don’t do anything

### ISSUE THREAD

**Issue by vermileoo** [SIsilicon/WorldEdit-BE#157] opened 2023-01-17 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The command, /tag @s add worldedit, works. I tried to use the ;kit command but nothing happened. I also tried ;wand and it didn’t do anything. Is there anything I can do to fix this?

### Expected behaviour

when using ;kit and ;wand you’re supposed to get the wooden axe that is needed for the mod.

### Minecraft version

1.19.51

### Device and operating system

iPhone 12

### Additional info

![65E768CC-7AA5-4565-AE45-9CE98C2ADAB4](https://user-images.githubusercontent.com/122871585/212869902-aeaf3b51-5816-4f9c-b171-61d7051af2f9.png)
![3DC0DE3F-C9C5-499B-A977-2098E095639F](https://user-images.githubusercontent.com/122871585/212869950-a2668954-7465-4e16-b90d-eaf4157e9839.png)
![26D11726-E247-4E5B-8458-FD55C7C777BC](https://user-images.githubusercontent.com/122871585/212869962-c82bd3e5-5a95-4d26-99c7-ee9c801bea13.png)
![0D189957-A8BD-48E1-9C60-4A13D275FDEF](https://user-images.githubusercontent.com/122871585/212869972-daf0d299-e023-4fe8-ad88-aaae4c22e1a0.png)

**Comment by SIsilicon** [comment] 2023-01-17 14:58
Duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/134

**Comment by SIsilicon** [comment] 2023-01-17 14:59
Duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/134

**Closed by SIsilicon** 2023-01-17 14:58 UTC
Labels: bug
