### ISSUE TITLE
cant use worldedit on realm

### ISSUE THREAD

**Issue by colinviersechs** [SIsilicon/WorldEdit-BE#173] opened 2023-03-03 22:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I uploaded my world with worldedit which was working perfectly fine at the beginning to my realm and on the realm it doesnt work i tried to use ;wand but it gave no response i reuploaded it multiple times and deleted worldedit and added it again still not working

### Expected behaviour

i expected it to work

### Steps to reproduce

1. go in realm settings
2. select world
3. replace world
4. select world
5. upload it
6. join realm
7. dont work

### Minecraft version

1.19.62

### Device and operating system

Windows 11

**Comment by SIsilicon** [comment] 2023-08-20 01:08
Duplicate of https://github.com/SIsilicon/WorldEdit-BE/issues/134

**Closed by SIsilicon** 2023-08-20 01:08 UTC
Labels: bug, unconfirmed
